import { ServiceType, VehicleCategory } from '@/types';

export const SERVICE_TYPES: ServiceType[] = [
  {
    id: 'airport-santiago',
    name: 'Traslado Aeropuerto - Santiago',
    code: 'airport_santiago',
    description: 'Traslado desde/hacia el aeropuerto con recepción personalizada',
    base_price: 25000,
    pricing_unit: 'fixed',
    includes: ['Peajes', 'Tags', 'Estacionamientos', 'Letrero corporativo', 'Seguimiento GPS'],
    is_active: true,
  },
  {
    id: 'city-km',
    name: 'Traslado dentro de Santiago',
    code: 'city_km',
    description: 'Traslado urbano con tarifa por kilómetro',
    base_price: 800,
    pricing_unit: 'per_km',
    includes: ['Seguimiento GPS', 'Sin recargos nocturnos'],
    is_active: true,
  },
  {
    id: 'package-delivery',
    name: 'Servicio de Encomiendas',
    code: 'package_delivery',
    description: 'Entrega de encomiendas hasta 5 kg',
    base_price: 8000,
    pricing_unit: 'fixed',
    includes: ['Hasta 5 kg', 'Seguimiento GPS', 'Confirmación de entrega'],
    is_active: true,
  },
  {
    id: 'driver-8h',
    name: 'Servicio de Chofer 8 horas',
    code: 'driver_8h',
    description: 'Chofer con disponibilidad completa por 8 horas',
    base_price: 120000,
    pricing_unit: 'fixed',
    includes: ['Disponibilidad completa', 'Combustible', 'Seguimiento GPS'],
    is_active: true,
  },
  {
    id: 'extra-hour',
    name: 'Hora Extra de Chofer',
    code: 'extra_hour',
    description: 'Hora adicional de servicio',
    base_price: 15000,
    pricing_unit: 'per_hour',
    includes: ['Combustible', 'Seguimiento GPS'],
    is_active: true,
  },
  {
    id: 'waiting-time',
    name: 'Tiempo de Espera',
    code: 'waiting_time',
    description: 'Tiempo de espera adicional a partir de 30 minutos',
    base_price: 5000,
    pricing_unit: 'per_30min',
    includes: ['A partir de 30 minutos'],
    is_active: true,
  },
  {
    id: 'emergency-vehicle',
    name: 'Vehículo de Emergencia',
    code: 'emergency_vehicle',
    description: 'Servicio express bajo solicitud',
    base_price: 30000,
    pricing_unit: 'fixed',
    includes: ['Servicio express', 'Respuesta inmediata', 'Seguimiento GPS'],
    is_active: true,
  },
];

export const VEHICLE_CATEGORIES: VehicleCategory[] = [
  {
    id: 'sedan-ejecutivo',
    name: 'Sedán Ejecutivo',
    code: 'sedan_ejecutivo',
    description: 'Vehículo sedán cómodo para ejecutivos',
    max_passengers: 4,
    luggage_capacity: '2 maletas grandes',
    features: ['Aire acondicionado', 'GPS', 'Seguro por asiento', 'Conductor profesional'],
    base_price_multiplier: 1.0,
    examples: ['Toyota Corolla', 'Nissan Sentra', 'Hyundai Elantra'],
  },
  {
    id: 'sedan-lujo',
    name: 'Sedán de Lujo',
    code: 'sedan_lujo',
    description: 'Vehículo sedán premium para servicios especiales',
    max_passengers: 4,
    luggage_capacity: '2 maletas grandes',
    features: ['Aire acondicionado', 'GPS', 'Seguro por asiento', 'Conductor profesional', 'Asientos de cuero', 'WiFi'],
    base_price_multiplier: 1.5,
    examples: ['Mercedes Benz E220', 'BMW Serie 3', 'Audi A4'],
  },
  {
    id: 'minivan-ejecutiva',
    name: 'Minivan Ejecutiva',
    code: 'minivan_ejecutiva',
    description: 'Vehículo espacioso para grupos pequeños',
    max_passengers: 8,
    luggage_capacity: '4 maletas grandes',
    features: ['Aire acondicionado', 'GPS', 'Seguro por asiento', 'Conductor profesional', 'Espacio adicional'],
    base_price_multiplier: 1.3,
    examples: ['Kia Grand Carnival', 'Toyota Hiace', 'Hyundai H1'],
  },
  {
    id: 'minivan-lujo',
    name: 'Minivan de Lujo',
    code: 'minivan_lujo',
    description: 'Vehículo premium para grupos que requieren comodidad superior',
    max_passengers: 8,
    luggage_capacity: '4 maletas grandes',
    features: ['Aire acondicionado', 'GPS', 'Seguro por asiento', 'Conductor profesional', 'Asientos de cuero', 'WiFi', 'Entretenimiento'],
    base_price_multiplier: 1.8,
    examples: ['Mercedes V-Class', 'BMW X7', 'Audi Q7'],
  },
  {
    id: 'suv-ejecutiva',
    name: 'SUV Ejecutiva',
    code: 'suv_ejecutiva',
    description: 'Vehículo SUV para comodidad y versatilidad',
    max_passengers: 7,
    luggage_capacity: '3 maletas grandes',
    features: ['Aire acondicionado', 'GPS', 'Seguro por asiento', 'Conductor profesional', 'Tracción 4x4', 'Altura superior'],
    base_price_multiplier: 1.4,
    examples: ['Hyundai Santa Fe', 'Toyota RAV4', 'Kia Sorento'],
  },
  {
    id: 'sprinter',
    name: 'Sprinter',
    code: 'sprinter',
    description: 'Vehículo de alta capacidad para grupos grandes',
    max_passengers: 19,
    luggage_capacity: '8 maletas grandes',
    features: ['Aire acondicionado', 'GPS', 'Seguro por asiento', 'Conductor profesional', 'Espacio amplio', 'Acceso fácil'],
    base_price_multiplier: 2.0,
    examples: ['Mercedes Sprinter', 'Ford Transit', 'Iveco Daily'],
  },
];

export const LICENSE_TYPES = [
  { code: 'A-2', name: 'Licencia A-2', description: 'Vehículos de transporte público y privado' },
  { code: 'A-3', name: 'Licencia A-3', description: 'Vehículos de carga y pasajeros' },
  { code: 'A-4', name: 'Licencia A-4', description: 'Vehículos de transporte escolar' },
  { code: 'A-5', name: 'Licencia A-5', description: 'Vehículos de emergencia y especiales' },
];

export const RESERVATION_STATUSES = [
  { code: 'pending', name: 'Pendiente', color: 'yellow', description: 'Reserva creada, esperando confirmación' },
  { code: 'confirmed', name: 'Confirmado', color: 'blue', description: 'Reserva confirmada por el sistema' },
  { code: 'in_progress', name: 'En Progreso', color: 'orange', description: 'Servicio en ejecución' },
  { code: 'completed', name: 'Completado', color: 'green', description: 'Servicio completado exitosamente' },
  { code: 'cancelled', name: 'Cancelado', color: 'red', description: 'Reserva cancelada' },
];

export const PAYMENT_STATUSES = [
  { code: 'pending', name: 'Pendiente', color: 'yellow', description: 'Pago pendiente' },
  { code: 'paid', name: 'Pagado', color: 'green', description: 'Pago completado' },
  { code: 'failed', name: 'Fallido', color: 'red', description: 'Pago fallido o rechazado' },
];

export const COMPANY_INFO = {
  name: 'Transportes Torres SpA',
  rut: '77.772.239-5',
  phone: '+56996476354',
  email: 'jennymolinaarce@gmail.com',
  address: 'Santiago, Chile',
  description: 'Empresa especializada en transporte ejecutivo y logístico con más de 8 años de experiencia',
  features: [
    'Operación 24/7 los 365 días del año',
    'Conductores con licencia A-2 y experiencia mínima de 2 años',
    'Flota con vehículos máximo 3 años de antigüedad',
    'Sistema de rastreo GPS en todas las unidades',
    'Seguro de asiento para cada pasajero',
    'Protocolos de seguridad y prevención',
    'Reportes mensuales de desempeño',
    'Central de reservas operativa 24/7',
  ],
}; 